name: 'GitHub Docker Action'
description: 'Build and publish your repository as a Docker image and push it to GitHub Package Registry in one step'
inputs:
  username:
    description: 'GitHub user to publish the image on behalf of.'
    required: true
  personalAccessToken:
    description: 'GitHub Personal Access Token for the user.'
    required: true
  repositoryName:
    description: 'The repository to push the image to. Defaults to current repository. Must be specified in format user/repo'
    required: false
  imageName:
    description: 'The desired name for the image. Defaults to current repository name.'
    required: false
  imageTag:
    description: 'The desired tag for the image. Defaults to current branch or release version number.'
    required: false
  context:
    description: 'Where to build the image'
    required: false
outputs:
  imageURL:
    description: 'The URL of the image.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'anchor'
  color: 'blue'
